apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-pod
  namespace: ns-2
  labels:
    app: my-configmap-app
spec:
  containers:
  - name: my-configmap-pod-container
    image: busybox
    command: ['sh', '-c', 'echo $(KEY1) && echo $(KEY2) && sleep 1200']
    env: 
    - name: KEY1
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: key1
    - name: KEY2
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: key2
