apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-volume-pod
  labels:
    app: my-configmap-volume-app
  namespace: ns-2
spec:
  containers:
  - name: my-configmap-volume-container
    image: busybox
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    command: ['sh', '-c', 'echo $(cat /etc/config/key1) && echo $(cat /etc/config/key2) && sleep 1200']
  volumes:
  - name: config-volume
    configMap:
      name: my-configmap

