apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
  namespace: ns-2
  labels:
    app: my-ckad-app
spec:
  containers:
  - name: my-secret-pod-container-1
    image: ubuntu
    command: ['sh', '-c', 'echo $(password) && echo $(encryptionKey) && sleep 1000'] 
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "750m"
    env:
    - name: password
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
    - name: encryptionKey
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: encryptionKey

