apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv
spec: 
  storageClassName: node-storage
  capacity: 
    storage: 512Mi
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: "/mnt/data"    
