apiVersion: v1
kind: Pod
metadata: 
  name: volume-pod
spec: 
  containers: 
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 2000']
    volumeMounts: 
    - mountPath: /tmp/storage
      name: my-volume  
  volumes: 
  - name: my-volume
    emptyDir: {}  
