apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kubernetes.io/change-cause":"kubectl apply --filename=rolling-update.yml --record=true"},"labels":{"app":"my-ckad-app","tier":"web-nginx"},"name":"rolling-update","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"tier":"web-nginx"}},"template":{"metadata":{"labels":{"tier":"web-nginx"},"name":"rolling-update-pod"},"spec":{"containers":[{"image":"nginx:1.8","livenessProbe":{"httpGet":{"path":"/","port":80}},"name":"rolling-update-container","ports":[{"containerPort":80}]}]}}}}
    kubernetes.io/change-cause: kubectl edit deployment rolling-update --record=true
  creationTimestamp: "2021-07-28T11:30:59Z"
  generation: 6
  labels:
    app: my-ckad-app
    tier: web-nginx
  name: rolling-update
  namespace: default
  resourceVersion: "649962"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/rolling-update
  uid: 482e1ecf-ef97-11eb-8498-080027f80ce7
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      tier: web-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        tier: web-nginx
      name: rolling-update-pod
    spec:
      containers:
      - image: nginx:1.9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: rolling-update-container
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2021-07-28T11:34:30Z"
    lastUpdateTime: "2021-07-28T11:34:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-28T11:30:59Z"
    lastUpdateTime: "2021-07-28T11:35:45Z"
    message: ReplicaSet "rolling-update-87c76b5b7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
