apiVersion: v1
kind: Pod
metadata: 
  name: readiness-pod
spec: 
  containers: 
  - name: readiness-pod-nginx
    image: nginx
    readinessProbe: 
      httpGet: 
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      httpGet: 
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5  
      
