apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    command: ['sh', '-c', 'sleep 4000']
    envFrom: 
    - configMapRef: 
        name: test-cm
    - secretRef: 
        name: test-secret      
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
