apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod-single
  namespace: udemy
  labels:
    app: my-ckad-app
spec:
  containers:
  - name: configmap-pod-single-container
    image: busybox
    command: ["env"]
    env:
      - name: db
        valueFrom:
          configMapKeyRef:
            name: dev-config
            key: database    
