apiVersion: v1
kind: Service
metadata: 
  name: nginx-service 
  labels: 
    app: my-ckad-app 
    tier: web-tier
spec: 
  type: NodePort
  selector: 
    tier: web-tier
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30007
