apiVersion: v1
kind: ReplicationController
metadata:
  name: ckad-app-rc
  labels:
    app: ckad-app
    type: front-end
spec:
  template:
    metadata:
      name: ckad-app-pod
      labels:
        app: ckad-app
        type: front-end
    spec:
      containers:
      - name: nginx-pod-rc
        image: nginx
  replicas: 3        
