apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ckad-rs
  labels:
    app: ckad-app
    type: front-end
spec:
  template:
    metadata:
      name: ckad-rs-pod
      labels:
        app: ckad-rs
        type: front-end
    spec:
      containers:
      - name: ckad-rs-container
        image: nginx
  replicas: 5
  selector: 
    matchLabels:
      type: front-end  


