apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
  labels: 
    app: my-ckad-app
spec: 
  schedule: "*/1 * * * *"
  jobTemplate: 
    spec: 
      template: 
        spec: 
          containers:
          - name: cron-job
            image: busybox
            command: ['sh', '-c', 'echo Hello Dude']
          restartPolicy: Never
