apiVersion: v1
kind: Pod
metadata:
  name: my-liveness-pod
  namespace: ns-3
  labels:
    app: my-ckad-app
spec: 
  containers: 
  - name: my-liveness-pod-container
    image: busybox
    command: ['sh', '-c', 'echo Hello K*S, && sleep 1800']
    livenessProbe:
      exec:
        command:
          - echo
          - testing
      initialDelaySeconds: 5
      periodSeconds: 10     
