apiVersion: v1
kind: Pod
metadata:
  name: my-readiness-pod
  namespace: ns-3
  labels:
    app: my-ckad-app
spec:
  containers:
  - name: my-readiness-pod-container
    image: nginx
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 20
