apiVersion: v1
kind: Pod
metadata:
  name: nginx-broken-pod
  namespace: ns-3
  labels: 
    app: my-ckad-app
spec:
  containers:
  - name: nginx
    image: nginx:5454545
    livenessProbe:
      httpGet:
        path: /
        port: 80
