apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  namespace: ns-1
  labels:
    app: first-app-v2
spec:
  containers:
  - name: first-app-container
    image: busybox
    command: ['sh', '-c', 'echo CKAD FTW Yo first container && sleep 15']
