apiVersion: v1
kind: Pod
metadata:
  name: my-arg-pod
  namespace: ns-1
  labels:
    app: myapp
spec:
  containers:
  - name: my-app-container
    image: busybox
    command: ['echo']
    args: ['Ye wala container']
  restartPolicy: Never
