apiVersion: v1
kind: Pod
metadata:
  name: my-containerport-pod
  namespace: ns-1
  labels:
    app: my-app
spec:
  containers:
  - name: my-containerport-pod
    image: nginx
    ports:
    - containerPort: 80
