apiVersion: v1
kind: Pod
metadata:
  name: my-command
  namespace: ns-1
  labels:
    app: my-app
spec:
  containers:
  - name: my-app-container
    image: busybox
    command: ['echo']
  restartPolicy: Never
