apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      parallelism: 2
      completions: 2
      template:
        spec:
          containers:
          - name: cron-tab-container
            image: busybox
          restartPolicy: Never
